INSERT INTO CURRENCY_EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, PORT)
VALUES (1,'USD','INR',65.0,8080);
INSERT INTO CURRENCY_EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, PORT)
VALUES (2,'EUR','INR',75.0,8080);
INSERT INTO CURRENCY_EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, PORT)
VALUES (3,'AUD','INR',25.0,8080);